spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.11.118/newmain?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 172.16.11.118
    port: 6379
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

key: 123456
